{% set name = "google-cloud-os-login" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_os_login-{{ version }}.tar.gz
  sha256: 2c27b838ae28dc13bc0bf20b91d6311bcb161735c8c527b49a11a50905fd7c0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    # constraining python <3.14 until grpcio >= 1.75.1 (required upstream) is available on conda-forge
    - python >={{ python_min }},<3.14
    - google-api-core >=1.34.1,<3.0.0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    - grpcio >=1.33.2,<2.0.0
    # more restrictive version for python 3.13
    - proto-plus >=1.25.0,<2.0.0
    - protobuf >=3.20.2,<7.0.0,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - grpc
    - google.cloud.oslogin
    - google.cloud.oslogin_v1
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-os-login
  summary: Google Cloud Os Login API client library
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: "Google Cloud OS Login API is a Google Cloud service that lets you manage SSH access to your instances using IAM without having to create and manage individual SSH keys. OS Login maintains a consistent Linux user identity across VM instances and is the recommended way to manage many users across multiple instances
    or projects.\nSee the [quick start guide](https://googleapis.dev/python/oslogin/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/oslogin/latest/index.html
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-os-login

extra:
  recipe-maintainers:
    - parthea
    - xylar
